name: normal
description: A starting point for Dart libraries or applications.
version: 0.5.0
homepage: https://bitbucket.org/ram6ler/normal/src/master/
author: Richard Ambler <rambler@ibwya.net>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
#  test: ^1.0.0
