name: normal
description: A simple library for working with the normal probability distribution. Includes methods for Gaussian density, cumulative probability, quantiles and random number generation.
version: 0.6.0
homepage: https://bitbucket.org/ram6ler/normal/src/master/

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
#  test: ^1.0.0
